export interface ICourse {
    id: number,
    name: string,
    status: string,
    start_at: string,
    end_at: string,
    super_brand: any,
    total_classes: number,
    enrolled: boolean,
    description: string,
    classes: any,
    category: string,
    teacher: string,
    teacher_avatar: string,
}